model_name_or_path: Qwen/Qwen3-4B-Instruct-2507
train_file: ../data/train-2.jsonl
output_dir: ../outputs

# Optional evaluation file. Provide a path or leave commented.
# eval_file: ../eval.jsonl

seed: 42
test_split_percentage: 5.0

max_length: 4096
pad_to_max_length: false
preprocessing_num_workers: null

per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
num_train_epochs: 1
learning_rate: 2.0e-5
weight_decay: 0.0
warmup_ratio: 0.0
max_grad_norm: 1.0

deepspeed_config: ../deepspeed/zero1.json
bf16: true
fp16: false
gradient_checkpointing: true
flash_attn: false
resume_from_checkpoint: null

save_steps: 200
save_total_limit: 3
logging_steps: 10
eval_steps: 200
evaluation_strategy: steps
report_to:
  - wandb
